In [1]:
# numpy
!pip install numpy

In [2]:
import numpy as np

ar = np.array([0,1,2,3,4,5,6,7,8,9]); ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# nupmy.ndarray ; n-dimensional array
# list 와 달리 모든 원소가 같은 자료형이어야 한다. 대신, 연속적인 메모리를 가지므로 연산 속도가 빠르다.
type(ar)

numpy.ndarray

In [9]:
?np.ndarray

Init signature: np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer int

In [27]:
# vectorization & easier operation
l1 = list(range(1,11))
l2 = list(range(11,21))

# 각 원소에 2를 곱한 배열
a = np.array(l1)
print(2 * a)

# 2 * a + b
b = np.array(l2)
print(2 * a + b, type(a), type(b))

# boolean operation
print(a == 5, b > 15)

[ 2  4  6  8 10 12 14 16 18 20]
[13 16 19 22 25 28 31 34 37 40] <class 'numpy.ndarray'> <class 'numpy.ndarray'>
[False False False False  True False False False False False] [False False False False False  True  True  True  True  True]


In [35]:
# 2-dimensional
c = np.array([[1,2,3],[10,11,12]])
print(len(c), len(c[0])) # 2, 3
print(c.ndim, c.shape) # 2 (2, 3)


# 3-dimensional
d = np.array([[[1,2,3],[10,11,12]],[[1,2,3],[10,11,12]],[[1,2,3],[10,11,12]],[[1,2,3],[10,11,12]]])
print(len(d), len(d[0]), len(d[0,1])) # 4, 2, 3
print(d.ndim, d.shape) # 3 (4, 2, 3)

2 3
2 (2, 3)
4 2 3
3 (4, 2, 3)


In [49]:
# slicing
test = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(test[0,:])	# 첫번째 행 전체
print(test[:,1])	# 두번째 열 전체
print(test[1,1:])	# 두번째 행의 두번째 열부터 끝 열까지
print(test[:2,:2])	# 2열까지

[0 1 2 3]
[1 5]
[5 6 7]
[[0 1]
 [4 5]]


In [77]:
# array(facny) indexing - 정수,boolean 으로 query 하는 방법

## boolean
bbb = np.array([11,12,13,14,15,16,17,18,19,20])
idx = np.array([False,True,False,True,False,True,False,True,False,True])
print(bbb[idx]) # 짝수만 발라내기
print(bbb[bbb%2 == 0]) # 동일결과

## 정수
bbb[np.array([4,3,2,1])]

## 다차원
da = np.array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

print(da[:,[True,False,True,False]])
print(da[[False,True,False],:])



[12 14 16 18 20]
[12 14 16 18 20]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[5 6 7 8]]


In [85]:
# 자료형
x = np.array([1,2,3])
x.dtype # int64

y = np.array([1.0, 2.0, 3.0])
y.dtype # float64

z = np.array([1,2.0,3])
z.dtype # float64

print(np.array([1.1, 2.1, 3.1], dtype='i')) # [1,2,3], dtype one of (i, i8, u, u8, c, c16, O, 0, S, S24, U, U24)

[1 2 3]


In [91]:
# inf & nan
np.array([0,1,-1,0]) / np.array([1,0,0,0]) # [0.0, inf, -inf, nan]

/var/folders/2j/hc1tn4p579n_s_wz02kjwnz00000gn/T/ipykernel_69945/3895389483.py:2: RuntimeWarning: divide by zero encountered in divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0]) # [0.0, inf, -inf, nan]
/var/folders/2j/hc1tn4p579n_s_wz02kjwnz00000gn/T/ipykernel_69945/3895389483.py:2: RuntimeWarning: invalid value encountered in divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0]) # [0.0, inf, -inf, nan]


array([  0.,  inf, -inf,  nan])

In [129]:
# utility

## zeros
print(np.zeros(5))
print(np.zeros((2,3)))
print(np.zeros((2,3), dtype="i"))
print(np.zeros((2,3), dtype="U4")) # 유니코드 4자 [['' '' '']['' '' '']]
uzeros = np.zeros((2,3), dtype="U4")
uzeros[1][2]='ABCDEFG'; uzeros # 유니코드 4자를 넘어가면 잘린다.

## ones
p = np.ones((2,3,4), dtype="i8")
q = np.ones_like(p, dtype="f")

# empty (초기화 하지 않음, 쓰레기값 보존)
r = np.empty((2,3,4))

# arange (numpy version range)
np.arange(10)
np.arange(3,21,2) # array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])


# linspace, logspace
np.linspace(0,100,5) # array([  0.,  25.,  50.,  75., 100.])
np.logspace(0.1, 1, 10) #array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766, 3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

# T (transpose)
A = np.array([[1,2,3],[10,20,30]])
A.T

# reshape
np.arange(0,63).reshape(7,9)
np.arange(0,63).reshape(7,-1) # 9를 -1로 대체할 수 있다.
np.arange(0,63).reshape(7,-1,3) # 9를 -1로 대체할 수 있다.

# flatten, ravel
np.arange(0,63).reshape(7,-1,3).flatten()
np.arange(0,63).reshape(7,-1,3).ravel()

# not equal! 
print(np.arange(5)) # 5
print(np.arange(5).reshape(1,5)) # (1,5)
print(np.arange(5).reshape(5,1)) # (5,1)

# 차원증가 (5 → (5,1))
print(np.arange(5)[:,np.newaxis])

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
[['' '' '']
 ['' '' '']]
[0 1 2 3 4]
[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
