In [1]:
# https://datascienceschool.net/01%20python/03.00%203%EC%9E%A5%20%EB%84%98%ED%8C%8C%EC%9D%B4%20%EB%B0%B0%EC%97%B4%20%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D.html
# numpy
!pip install numpy

     ---------------------------------------- 15.8/15.8 MB 5.0 MB/s eta 0:00:00



[notice] A new release of pip available: 22.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

ar = np.array([0,1,2,3,4,5,6,7,8,9]); ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# nupmy.ndarray ; n-dimensional array
# list 와 달리 모든 원소가 같은 자료형이어야 한다. 대신, 연속적인 메모리를 가지므로 연산 속도가 빠르다.
type(ar)

numpy.ndarray

In [4]:
?np.ndarray

Init signature: np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer int

In [5]:
# vectorization & easier operation
l1 = list(range(1,11))
l2 = list(range(11,21))

# 각 원소에 2를 곱한 배열
a = np.array(l1)
print(2 * a)

# 2 * a + b
b = np.array(l2)
print(2 * a + b, type(a), type(b))

# boolean operation
print(a == 5, b > 15)

[ 2  4  6  8 10 12 14 16 18 20]
[13 16 19 22 25 28 31 34 37 40] <class 'numpy.ndarray'> <class 'numpy.ndarray'>
[False False False False  True False False False False False] [False False False False False  True  True  True  True  True]


In [6]:
# 2-dimensional
c = np.array([[1,2,3],[10,11,12]])
print(len(c), len(c[0])) # 2, 3
print(c.ndim, c.shape) # 2 (2, 3)


# 3-dimensional
d = np.array([[[1,2,3],[10,11,12]],[[1,2,3],[10,11,12]],[[1,2,3],[10,11,12]],[[1,2,3],[10,11,12]]])
print(len(d), len(d[0]), len(d[0,1])) # 4, 2, 3
print(d.ndim, d.shape) # 3 (4, 2, 3)

2 3
2 (2, 3)
4 2 3
3 (4, 2, 3)


In [7]:
# slicing
test = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(test[0,:])	# 첫번째 행 전체
print(test[:,1])	# 두번째 열 전체
print(test[1,1:])	# 두번째 행의 두번째 열부터 끝 열까지
print(test[:2,:2])	# 2열까지

[0 1 2 3]
[1 5]
[5 6 7]
[[0 1]
 [4 5]]


In [8]:
# array(facny) indexing - 정수,boolean 으로 query 하는 방법

## boolean
bbb = np.array([11,12,13,14,15,16,17,18,19,20])
idx = np.array([False,True,False,True,False,True,False,True,False,True])
print(bbb[idx]) # 짝수만 발라내기
print(bbb[bbb%2 == 0]) # 동일결과

## 정수
bbb[np.array([4,3,2,1])]

## 다차원
da = np.array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

print(da[:,[True,False,True,False]])
print(da[[False,True,False],:])



[12 14 16 18 20]
[12 14 16 18 20]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[5 6 7 8]]


In [9]:
# 자료형
x = np.array([1,2,3])
x.dtype # int64

y = np.array([1.0, 2.0, 3.0])
y.dtype # float64

z = np.array([1,2.0,3])
z.dtype # float64

print(np.array([1.1, 2.1, 3.1], dtype='i')) # [1,2,3], dtype one of (i, i8, u, u8, c, c16, O, 0, S, S24, U, U24)

[1 2 3]


In [10]:
# inf & nan
np.array([0,1,-1,0]) / np.array([1,0,0,0]) # [0.0, inf, -inf, nan]

C:\Users\USER\AppData\Local\Temp\ipykernel_15844\3895389483.py:2: RuntimeWarning: divide by zero encountered in divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0]) # [0.0, inf, -inf, nan]
C:\Users\USER\AppData\Local\Temp\ipykernel_15844\3895389483.py:2: RuntimeWarning: invalid value encountered in divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0]) # [0.0, inf, -inf, nan]


array([  0.,  inf, -inf,  nan])

In [13]:
# utility

## zeros
print(np.zeros(5))
print(np.zeros((2,3)))
print(np.zeros((2,3), dtype="i"))
print(np.zeros((2,3), dtype="U4")) # 유니코드 4자 [['' '' '']['' '' '']]
uzeros = np.zeros((2,3), dtype="U4")
uzeros[1][2]='ABCDEFG'; uzeros # 유니코드 4자를 넘어가면 잘린다.

## ones
p = np.ones((2,3,4), dtype="i8")
q = np.ones_like(p, dtype="f")

# empty (초기화 하지 않음, 쓰레기값 보존)
r = np.empty((2,3,4))

# arange (numpy version range)
np.arange(10)
np.arange(3,21,2) # array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])


# linspace, logspace
np.linspace(0,100,5) # array([  0.,  25.,  50.,  75., 100.])
np.logspace(0.1, 1, 10) #array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766, 3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
[['' '' '']
 ['' '' '']]


array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [28]:
a = np.arange(0,12).reshape(6,-1)
print(a)

# 전치연산
## T (transpose)
print(a.T)

# reshape
print(a.reshape(3,-1)) # -1 필요한 수를 자동으로 넣어준다
print(a.reshape(2,3,-1))

# flatten, ravel
print(a.flatten(), a.ravel())

# not equal! 
print(np.arange(5)) # 5
print(np.arange(5).reshape(1,5)) # (1,5)
print(np.arange(5).reshape(5,1)) # (5,1)

# 차원증가 (5 → (5,1))
print(np.arange(5)[:,np.newaxis])

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11] [ 0  1  2  3  4  5  6  7  8  9 10 11]
[0 1 2 3 4]
[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0]
 [1]
 [2]
 [3]
 [4]]


In [56]:
# 배열연결

## hstack (horizontal) : (2x3) * (2x2) -> (2x5)
a1 = np.ones((2,3)); print(a1)
a2 = np.zeros((2,2)); print(a2)
print(np.hstack([a1,a2]))

## vstack (vertical) : (2x3) * (3x3) -> (5x3)
b1 = np.zeros((3,3)); print(b1)
print(np.vstack([a1,b1]))

# dstack (depth) : (4x5) * (4x5) -> (4x5x2)
c1 = np.zeros((4,5)); print(c1)
c2 = np.ones((4,5))
print(np.dstack([c1,c2]))

# stack (depth, with sepcific direciton)
print(np.stack([c1,c2]))          # shape : (2,4,5)
print(np.stack([c1,c2], axis=1))  # shape : (4,2,5)
print(np.stack([c1,c2], axis=2))  # shape : (4,5,2)

# r_ (indexer) : vstack 동일?!
print(np.r_[a1,b1])

# c_

#tile



[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[[0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1.]]]
[[[0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]]]
[[1. 1. 1.]
 [1.

In [60]:
# grid point

x = np.arange(3) # 0~2
y = np.arange(5) # 0~4
X,Y = np.meshgrid(x,y)
print(X)
print(Y)

[list(zip(x,y)) for x,y in zip(X,Y)]

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [62]:
# 3.3 배열의연산

## 벡터화 연산
x=np.arange(1,10001)
y=np.arange(10001,20001)

In [66]:
%%time
z1 = np.zeros_like(x)
for i in range(10000):
    z1[i] = x[i] + y[i]
z1[:10]

CPU times: total: 0 ns
Wall time: 2.02 ms


array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [68]:
%%time
z2 = x + y
z2[:10]

CPU times: total: 0 ns
Wall time: 0 ns


array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [69]:
%%time
x == y

CPU times: total: 0 ns
Wall time: 0 ns


array([False, False, False, ..., False, False, False])

In [70]:
%%time
y == x+10000

CPU times: total: 15.6 ms
Wall time: 1 ms


array([ True,  True,  True, ...,  True,  True,  True])

In [75]:
%%time
np.all(y == x) # 모두가 동일한지 확인

CPU times: total: 0 ns
Wall time: 0 ns


False

In [92]:
%%time
a = np.arange(1000)
print(np.exp(a), 10**a, np.log(a+1)) # 자연지수, 지수, 로그

[1.00000000e+000 2.71828183e+000 7.38905610e+000 2.00855369e+001
 5.45981500e+001 1.48413159e+002 4.03428793e+002 1.09663316e+003
 2.98095799e+003 8.10308393e+003 2.20264658e+004 5.98741417e+004
 1.62754791e+005 4.42413392e+005 1.20260428e+006 3.26901737e+006
 8.88611052e+006 2.41549528e+007 6.56599691e+007 1.78482301e+008
 4.85165195e+008 1.31881573e+009 3.58491285e+009 9.74480345e+009
 2.64891221e+010 7.20048993e+010 1.95729609e+011 5.32048241e+011
 1.44625706e+012 3.93133430e+012 1.06864746e+013 2.90488497e+013
 7.89629602e+013 2.14643580e+014 5.83461743e+014 1.58601345e+015
 4.31123155e+015 1.17191424e+016 3.18559318e+016 8.65934004e+016
 2.35385267e+017 6.39843494e+017 1.73927494e+018 4.72783947e+018
 1.28516001e+019 3.49342711e+019 9.49611942e+019 2.58131289e+020
 7.01673591e+020 1.90734657e+021 5.18470553e+021 1.40934908e+022
 3.83100800e+022 1.04137594e+023 2.83075330e+023 7.69478527e+023
 2.09165950e+024 5.68572000e+024 1.54553894e+025 4.20121040e+025
 1.14200739e+026 3.104297

<timed exec>:2: RuntimeWarning: overflow encountered in exp


In [98]:
# broadcasting : scala, 또는 저차원 행렬을 연산에 맞게 반복 확장해줌

# scala 
a = np.arange(100).reshape(10,-1)
print(a*10-5)

# (2,3) + (2,1)
print(np.arange(6).reshape(2,-1) + np.array([[10],[20]]))

# (2,3) + (1,3)
print(np.arange(6).reshape(2,-1) + np.array([10,20,30]))

[[ -5   5  15  25  35  45  55  65  75  85]
 [ 95 105 115 125 135 145 155 165 175 185]
 [195 205 215 225 235 245 255 265 275 285]
 [295 305 315 325 335 345 355 365 375 385]
 [395 405 415 425 435 445 455 465 475 485]
 [495 505 515 525 535 545 555 565 575 585]
 [595 605 615 625 635 645 655 665 675 685]
 [695 705 715 725 735 745 755 765 775 785]
 [795 805 815 825 835 845 855 865 875 885]
 [895 905 915 925 935 945 955 965 975 985]]
[[10 11 12]
 [23 24 25]]
[[10 21 32]
 [13 24 35]]


In [139]:
# dimension reduction

# 전체 통계
a = (10*np.arange(10)+1).reshape(2,-1)
print(a)
print(np.sum(a), a.sum())
print(np.min(a), a.min(), np.argmin(a), a.argmin()) # 최솟값, 최솟값 위치
print(np.max(a), a.max(), np.argmax(a), a.argmax()) # 최댓값, 최댓값 위치
print(np.mean(a), a.mean())
print(np.median(a))

#  축 중심 통계
print(np.sum(a, axis=0), np.sum(a, axis=1))
print(np.min(a, axis=0), np.min(a, axis=1))
print(np.max(a, axis=0), np.max(a, axis=1))
print(np.mean(a, axis=0), np.mean(a, axis=1))
print(np.median(a, axis=0), np.median(a, axis=1))

# boolean
b = np.zeros((100,100), dtype=np.int_)
print(np.any(b == 1), (b==1).any())
print(np.all(b == 0), (b==0).all())

[[ 1 11 21 31 41]
 [51 61 71 81 91]]
460 460
1 1 0 0
91 91 9 9
46.0 46.0
46.0
[ 52  72  92 112 132] [105 355]
[ 1 11 21 31 41] [ 1 51]
[51 61 71 81 91] [41 91]
[26. 36. 46. 56. 66.] [21. 71.]
[26. 36. 46. 56. 66.] [21. 71.]
False False
True True


In [158]:
# sorting
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])

print(np.sort(a)) # axis=1 동일, 가로방향 정렬
print(np.sort(a, axis=0)) # 세로방향 정렬
print(np.sort(a, axis=1))
print(np.argsort(a)) # 정렬순서

[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]
[[ 1  3  1  7]
 [ 2 12  5  9]
 [ 4 15 11 14]]
[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]
[[1 0 2 3]
 [0 3 2 1]
 [2 0 3 1]]
